"""made admin name field optional

Revision ID: 0d72c732a9df
Revises: f7f3b6e10769
Create Date: 2025-06-04 20:39:39.105031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d72c732a9df'
down_revision: Union[str, None] = 'f7f3b6e10769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='The full name of the admin.')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='The full name of the admin.')

    # ### end Alembic commands ###
